[MUST REVERT]:Control_thread changes to fix kitkat build error.
Encountered the below build error during kitkat build:
In member function 'android::status_t android::ControlThread::
allocateGraMetaDataBuffers()':
error: 'MetadataBufferTypeGrallocSource' was not declared in
this scope.

This patch is a hack to ensure successful build. This needs to
be reverted.

Change-Id: Iac9823c8a4a2ce9b33d2f9a8fd9430fb021c1cea
Signed-off-by: Mohanraj S <mohanrajx.sakkaraiappan@intel.com>